### ISSUE TITLE
option to disable pylint

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode-pylint#15]
there should be a `python.pylintEnabled` option, like the `python.linting.pylintEnabled` option in the python extension.

currently i get pylint errors when i open projects that don't use pylint, so i have to manually disable the extension when using those projects and re-enable it when switching back to projects that do

**Comment by brettcannon** [comment]
You can [disable an extension](https://code.visualstudio.com/docs/editor/extension-marketplace#_disable-an-extension) on a per-workspace basis, so you shouldn't have to manually control for it at a global level beyond deciding if you want an extension enabled or disabled most of the time.

**Comment by abdullzz** [comment]
this bug still exist years later @karthiknadig

**Comment by karthiknadig** [comment]
@abdullzz the comment here tells you how to do it https://github.com/microsoft/vscode-pylint/issues/15#issuecomment-1069693830
