### ISSUE TITLE
the extension does not work if add args to the "pylint.args"

### ISSUE THREAD

**Issue by meetAndEgg** [microsoft/vscode-pylint#163]
When the "pylint.args" is empty, this extension works well
<img width="1001" alt="LFZ8_077 1S_S HXHU6Q$F3" src="https://user-images.githubusercontent.com/104431511/184269963-b75172f5-f0dd-42bb-b0b0-4b3286a968f1.png">
But if I add args to the "pylint.args", this extension  does not work.
<img width="987" alt="0G`8JPN8~E{OCLXDA899} A" src="https://user-images.githubusercontent.com/104431511/184270215-f5fc9c6e-2d0e-48f7-a2e9-4f006607eddf.png">

**Comment by karthiknadig** [comment]
Please don't put space around the "=". You are also missing `--` for the `max-line-length`. Try:
```
"pylint.args": ["---disable=C0330,C0326", "--max-line-length=88"]
```

**Comment by karthiknadig** [comment]
You can look at `Output` > `Pylint` to see exactly what went wrong.

**Comment by meetAndEgg** [comment]
> You can look at `Output` > `Pylint` to see exactly what went wrong.

Get it!  I found this error in  OUTPUT  `Unrecognized option found: disable = C0330, C0326`.
After repairing my options, pylint works well again!
Thanks!

**Comment by meetAndEgg** [comment]
> You can look at `Output` > `Pylint` to see exactly what went wrong.

Get it!  I found this error in  OUTPUT  `Unrecognized option found: disable = C0330, C0326`.
After repairing my options, pylint works well again!
Thanks!
