### ISSUE TITLE
don't run on `.pyi` files by default

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode-pylint#174]
pylint currently doesn't support `.pyi` files, so this plugin should ignore them by default: https://github.com/PyCQA/pylint/issues/4987

i tried using `ignore-patterns` to work around this, but that doesn't seem to work either: #169

**Comment by luabud** [comment]
We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. If you're part of the event and would like to submit a contribution to this issue, please let us know, and we'll be happy to assign it to you.

For other community members who are not participating in the event, we appreciate your interest in contributing! We kindly request that you wait until after September 22nd to work on this issue. If no one from the event has been assigned to it by then, we'll gladly assign it to you. Thank you for your understanding and support!

**Comment by Ektaroy** [comment]
Hii @luabud,
I would like to work on this issue. Can you please assign it to me?

**Comment by Pierre-Sassoulas** [comment]
Please note that pylint compatible with astroid version above ``3.0.0a4`` or superior (pylint =>``3.0.0a7``) will recognize ``pyi`` files see, https://github.com/pylint-dev/astroid/pull/2182

**Comment by DetachHead** [comment]
closing this since pylint now partially supports pyi files
