### ISSUE TITLE
Add code action to format code when there's a "multiple statements" warning

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-pylint#178]
Ref: https://github.com/microsoft/vscode-pylint/issues/43

There are two things that needs to be done:

- [ ] Create quick fix for warning code `C0321:multiple-statements` that triggers the format document action
- [ ] Add unit test 

The code for the first step will be similar to the one here: https://github.com/microsoft/vscode-pylint/blob/2fae19e66aaf079c3dc190b81f913695ac65b078/bundled/tool/server.py#L243

And the unit tests will be similar to this: https://github.com/microsoft/vscode-pylint/blob/2fae19e66aaf079c3dc190b81f913695ac65b078/src/test/python_tests/test_code_actions.py#L23

**Comment by gagandeepp** [comment]
@luabud interested please assign
