### ISSUE TITLE
Re-order settings in package.json alphabetically

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-pylint#183]
Having the settings in alphabetical order makes it easier to scan through the list when looking for a setting.

**Comment by Pathholder1806** [comment]
Hey @luabud !
I would like to contribute to this issue.

Just wanted to ask that if you are talking about both **package.json** and **package.nls.json**  files

**Comment by kate-kee** [comment]
@luabud please assign it to me as part of GHC open source day.
