### ISSUE TITLE
Can't install release version of 'ms-python.pylint' extension because it has no release version.

### ISSUE THREAD

**Issue by WXZhao7** [microsoft/vscode-pylint#19]
I can't install vscode-pylint anyway. I have cleared my setting and close all extensions.
![image](https://user-images.githubusercontent.com/56864878/160966724-e8f45418-2bc7-40e3-a0ea-84a4b5da867d.png)

![image](https://user-images.githubusercontent.com/56864878/160966316-bcfe92f4-860e-4c2f-89eb-c200356e6945.png)

**Comment by karthiknadig** [comment]
@WXZhao7 `pylint` extension is currently in pre-release. So, please select the pre-release option from the drop down:
![image](https://user-images.githubusercontent.com/3840081/160974444-c9bbef8d-c124-4990-b4a5-72b25146b540.png)

**Comment by WXZhao7** [comment]
@karthiknadig Thanks! It seems that vscode-pylint extension works faster than pylint installed by conda. I enjoy it now:)

**Comment by asapsmc** [comment]
I'm getting the same error in Macos, and I'm already using pre-release versions of Pylance, Pylint, Python. 
<img width="1412" alt="image" src="https://github.com/microsoft/vscode-pylint/assets/6062179/dd252258-5d7c-4542-931f-616acce08724">

**Comment by karthiknadig** [comment]
@asapsmc `Debugpy` extension is in pre-release. If you want to install it you will need to use the drop down and select install pre-release. Please note that you have opened this issue in `pylint` repository which is not related to `debugpy`.
