### ISSUE TITLE
Add code actions to disable warnings with pylint 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-pylint#205]
> Additionally a second code action option for `#pylint: disable-next=<issue>`. The use case often being adding a comment will cause `line-too-long`.

> Thoughts? I can work on this. @karthiknadig @luabud

_Originally posted by @ketozhang in https://github.com/microsoft/vscode-pylint/issues/43#issuecomment-1288236013_

**Comment by ketozhang** [comment]
Thanks @luabud.

Preceding that comment was
> I'm suggesting an additional action: to ignore the pylint rule for that line by adding the inline comment `# pylint: disable=<issue>`.

_Originally posted by @ketozhang in https://github.com/microsoft/vscode-pylint/issues/43#issuecomment-1237521217_

**Comment by agalazis** [comment]
This is a must! Not there yet....

**Comment by Pierre-Sassoulas** [comment]
https://github.com/microsoft/vscode-pylint/issues/535 seems like a duplicate but there's a lot more details there.

**Comment by karthiknadig** [comment]
Follow https://github.com/microsoft/vscode-pylint/issues/535 for tracking this. 

Closing in favor of https://github.com/microsoft/vscode-pylint/issues/535
