### ISSUE TITLE
Easy and quick way to disable/change linter rule

### ISSUE THREAD

**Issue by eromoe** [microsoft/vscode-pylint#235]
I think many people doesn't know how to add and remove linter rule according to their project status .

For example, 
![image](https://user-images.githubusercontent.com/3938751/88500651-dfff1a80-cffb-11ea-9a5e-8a11fa946cea.png)

I want to 
1. disable error from gloabal variable ,  seems pylinter doesn't allow this by default , you need cost much time to search how to exclude this error . We could simply right click the error message to **[exclude this error rule]**.
2. quick disable linting for `pyspark`, I found some articles asked me to add some rules in `.pylintrc` to ignore modules , which doesn't work at all . We could simply right click the warnning message to **[add the ignore rule]**.
3. Other unresolved import is because linter doesn't know where is the project root , maybe there are many project roots , add those paths to `python.autoComplete.extraPaths` doesn't take effect . We could simply right click the warnning message to **[redirect us to config path , so that we can add the project/module path !]**
4. ...

copy from https://github.com/microsoft/vscode-python/issues/13167

**Comment by karthiknadig** [comment]
The right wat to set these up is to use `.pylintrc` for including and excluding rules. If that did not work in a particular scenario can you provide details on the location of `.pylintrc` in relation to the file that was being linted, and the root of the project. Pylint in most cases should pickup settings if they are in the root of workspace folder. 

As for extra paths, for this you should be using `--inithooks` argument with pylint.

We want you to configure pylint the same way you would in CI. This way there aren't two separate settings. With that in mind, the include and exclude rules here should probably go to the correct `.pylintrc` which the extension should be able to update using quick-fixes or some other command.

**Comment by karthiknadig** [comment]
Thanks for the feature request! We are going to give the community 60 days from when this issue was created to provide 5 👍 upvotes on the opening comment to gauge general interest in this idea. If there's enough upvotes then we will consider this feature request in our future planning. If there's unfortunately not enough upvotes then we will close this issue.

**Comment by karthiknadig** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
