### ISSUE TITLE
Problem tab doesn't show refactor issues

### ISSUE THREAD

**Issue by amitofir** [microsoft/vscode-pylint#236]
When running pylint command I'm getting much more hints of improvements than shown in the 'Problems' tab. It would be nice if all data were displayed in one place and according to the output from the command line pylint.

**Comment by brettcannon** [comment]
Can you please include a screenshot of what you mean? This extension only shows what Pylint tells us about, so there shouldn't be any "extra" info from this extension.

**Comment by karthiknadig** [comment]
Note that refactor issues are marked as Hints by default, you can update this in settings to report as problems.
https://github.com/microsoft/vscode-pylint/blob/6bd157787fd41ffa9b3f2b6f8f26a7cd7fdb7afc/package.json#L143-L151

**Comment by amitofir** [comment]
Ok, I didn't know that file. Thanks for helping
