### ISSUE TITLE
Environment pylint is used without `pylint.path` specified

### ISSUE THREAD

**Issue by alkatar21** [microsoft/vscode-pylint#29]
As far as I understood this extension is meant to speed up the linting by not taking the pylint version from the environment anymore, so that for example you don't have to run `conda run` every time as long as you don't specify `pylint.path`.
I had `pylint==2.12.2` installed in one environment and pylint 2.12.2 was used by the extension, which can be seen in the error ranges. An update of pylint in the env improved the as expected, however I had the feeling that only after removing pylint from the env the bundled pylint was used and it was then also subjectively faster.

Is this intentional behavior?
If yes, I would appreciate to document this.
Personally I would appreciate to always use the bundled one, as long as no `pylint.path` is specified, because in our case pylint is specified as dev dependency and therefore installed in the environment for the command line, but I would still like to use the speedup of the extension.

**Comment by karthiknadig** [comment]
Yes, this is intended behavior. I will be updating the docs to mention this. This behavior was based on a discussion with tooling developers (not specifically `pylint`), but the general recommendation was to use the version available in the environment first, and if not use the bundled version.
