### ISSUE TITLE
Switching to venv interpreter causes pylint lsp_server.py to fail

### ISSUE THREAD

**Issue by MiroFurtado** [microsoft/vscode-pylint#313]
When I switch to my python venv as the Python Interpreter for my remote vscode session, the pylint server fails.

From the output, I get

```
n loaded
2023-03-31 20:18:25.172 [info] Using cwd from 
2023-03-31 20:34:34.436 [info] Traceback (most recent call last):
  File "/home/coder/.vscode_extensions/ms-python.pylint-2023.4.0/bundled/tool/lsp_server.py", line 38, in <module>
    import lsp_utils as utils
  File "/home/coder/.vscode_extensions/ms-python.pylint-2023.4.0/bundled/tool/lsp_utils.py", line 33, in <module>
    for p in (as_list(site.getsitepackages()) + as_list(site.getusersitepackages()))
AttributeError: module 'site' has no attribute 'getsitepackages'
```

**Comment by karthiknadig** [comment]
This looks like your virtual env might be corrupted. The `site` package comes from standard python library. as long as you are using python 3.7 this should work.

**Comment by karthiknadig** [comment]
This can also happen if your python is 3.1 or older. https://docs.python.org/3/library/site.html#site.getsitepackages

**Comment by MiroFurtado** [comment]
Some versions of virtualenv add their own implementations of site package to override. I am on python 3.7

**Comment by karthiknadig** [comment]
Which specific virtual env implementation are you using? How did you create the virtual env?

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
