### ISSUE TITLE
[Question] What scenario is the extension intended for?

### ISSUE THREAD

**Issue by raulbocanegra** [microsoft/vscode-pylint#324]
Hi!
I am not using this extension yet. I already use the Python extension with pylint enabled by having the following line: `"python.linting.pylintEnabled": true` in my `settings.json`. Pylint results are visible on the Problems tab and works fine. 

So I was wondering if using this extensions adds any new feature or improvement over the scenario described above.

Thanks!

**Comment by karthiknadig** [comment]
This extension will replace the functionality provided by python extension.

Here are few advantages using this extension:
1. This ships with pylint in the box, there is no need to install pylint in every environment.
2. Issues reported by the extension are more detailed, with links to pylint help:
![image](https://user-images.githubusercontent.com/3840081/230660306-e6bb11c6-c40d-4d9c-970c-0a9eecb19c94.png)
3. We also provide code actions which fixes some of the issues reported by the extension.
4. The extension runs faster as it uses pylint in a server like mode, i.e, does not have to start a new process each time you save.
5. This is mostly written in python, and easier to contribute new features to.
6. `pylint` maintainers also follow this extension and help with triaging issues.
