### ISSUE TITLE
Disabling doesn't work

### ISSUE THREAD

**Issue by TheCarpetMerchant** [microsoft/vscode-pylint#340]
Here's what I've tried so far :
```
  "pylint.args": [
    "--disable=missing-module-docstring",
    "--disable=C0114",
  ],
```
![Screenshot (193)](https://github.com/microsoft/vscode-pylint/assets/5080204/ffe550c2-9e00-4878-9d28-4cf0777759e2)

The rest of my settings :
![Screenshot (194)](https://github.com/microsoft/vscode-pylint/assets/5080204/bab0b312-e9ea-418b-9993-f2ac69d388ae)

But the C0114 still shows up as an error :
![Screenshot (192)](https://github.com/microsoft/vscode-pylint/assets/5080204/cb78f706-078b-4ca0-9866-3556bec5597b)

**Comment by karthiknadig** [comment]
@TheCarpetMerchant Those are not the settings for this extension, please see the settings here: https://github.com/microsoft/vscode-pylint#settings

If you are using the pylint extension, then please share the logs.

**Comment by karthiknadig** [comment]
Here is the link to the extension if you want to install: https://marketplace.visualstudio.com/items?itemName=ms-python.pylint

**Comment by TheCarpetMerchant** [comment]
I switched to flake8 and it took me 1 minute 30 seconds to get it to ignore this lint, google search included. I'm sorry, but it's just better for me there's no contest.
