### ISSUE TITLE
Google firestore transactional decorator shows up as non-existent

### ISSUE THREAD

**Issue by Duncanr-glitch** [microsoft/vscode-pylint#354]
When I use the firebase_admin's firstore transactional decorator, it works perfectly well (since I actually have everything installed) but I get the following critical error message from pylint:

Module 'firebase_admin.firestore' has no 'transactional' member

I haven't seen this error with any other object from any other part of the firebase libraries,.

**Comment by karthiknadig** [comment]
This should be filed on pylint. We don't really do anything specific to this in the extension. https://github.com/pylint-dev/pylint/issues
