### ISSUE TITLE
How to use this extension for python2 project

### ISSUE THREAD

**Issue by Aya-Yang** [microsoft/vscode-pylint#355]
I have some projects still use python2 for historic reasons，but this extension not support python2 interpreter, how to solve it

**Comment by karthiknadig** [comment]
@Aya-Yang Try this and let me know.

1. Set `pylint.interpreter` to `python3` : `"pylint.interpreter": ["/usr/bin/python3"]`
2. Set `pylint.path` to pylint from python2 environment: `"pylint.path": ["<path-to-pylint-binary`"]
