### ISSUE TITLE
This setting will be deprecated soon

### ISSUE THREAD

**Issue by brendan8c** [microsoft/vscode-pylint#374]
After updating VSCode, these warnings appeared. How to be further? What to do?

My settings.json
```

    "python.linting.enabled": true, // This setting will be deprecated soon. Find out more here: https://aka.ms/AAlgvkb
    "python.linting.pylintEnabled": true, // This setting will be deprecated soon. Find out more here: https://aka.ms/AAlgvkb
    "python.linting.pylintArgs": [ // This setting will be deprecated soon. Find out more here: https://aka.ms/AAlgvkb
        "--rcfile=<путь_к_файлу_настроек_pylint>",
        "--load-plugins=<дополнительные_плагины>"
    ],
    "python.linting.pylintSeverity": { // Unknown configuration option
        "convention": "Information", // Unknown configuration option
        "error": "Error", // Unknown configuration option
        "fatal": "Error", // Unknown configuration option
        "refactor": "Hint", // Unknown configuration option
        "warning": "Warning", // Unknown configuration option
        "W0611": "Error", // Unknown configuration option
        "undefined-variable": "Warning" // Unknown configuration option
    },
    "python.linting.pylintPath": ["<путь_к_исполняемому_файлу_pylint>"], // This setting will soon be deprecated. Use the Pylint extension. Read more here: https://aka.ms/AAlgvkb
    "python.linting.pylintInterpreter": ["<путь_к_исполняемому_файлу_python>"], // Unknown configuration option
    "python.linting.pylintImportStrategy": "useBundled", // Unknown configuration option
    "python.linting.pylintShowNotification": "on", // Unknown configuration option
    "python.linting.lintOnChange": false, // Unknown configuration option
```

**Comment by karthiknadig** [comment]
@brendan8c Make sure you have installed this extension: https://marketplace.visualstudio.com/items?itemName=ms-python.pylint

The setting names are wrong see here for the right setting names:
https://github.com/microsoft/vscode-pylint#settings . For example, it is `pylint.importStrategy` not `python.pylint.importStrategy`.

Also, you don't need to add every setting only the ones you want to change.

**Comment by brendan8c** [comment]
Ok thank you. Have I entered the settings correctly?
```
  "python.pythonPath": "E:\\Program Files\\Python311\\python.exe",
  "pylint.interpreter": ["E:\\Program Files\\Python311\\python.exe"],
  "pylint.args": ["--rcfile=<file>"],
  "pylint.severity": {
    "convention": "Information",
    "error": "Error",
    "fatal": "Error",
    "refactor": "Hint",
    "warning": "Warning",
    "info": "Information",
    "W0611": "Error",
    "undefined-variable": "Warning"
  },
  "pylint.path": ["E:\\Program Files\\Python311\\Scripts\\pylint"],
  "pylint.importStrategy": "useBundled",
  "pylint.showNotification": "off",
  "pylint.lintOnChange": false,
```

**Comment by karthiknadig** [comment]
You don't need all the settings, you should only set those that you want to change. Most of the values there are default you don't need to set them. You can remove all of these settings.

For future, wherever you see `<file>` you need to replace that with actual path to the file. You don't need that setting if you are not using a config file for pylint.

Also, You don't need to set these unless you really need to. These settings are there to support some rare scenarios. You should remove these.
```
"python.pythonPath": "E:\\Program Files\\Python311\\python.exe",
"pylint.interpreter": ["E:\\Program Files\\Python311\\python.exe"],
"pylint.path": ["E:\\Program Files\\Python311\\Scripts\\pylint"],
```

**Comment by steveoh** [comment]
It seems I can set a default formatter, can I set a default linter?

There are at least 4 options and going between them in different projects seems impossible at the moment. What am I missing?

**Comment by karthiknadig** [comment]
@steveoh You can enable disable linter extensions at the workspace level. You can also make use of VS Code Profiles to load the extension you need in various scenarios.

**Comment by steveoh** [comment]
yes, but how can I set the vscode settings.json file to enable and disable the correct linters and formatters per project without having to manually mess with the extensions?

**Comment by steveoh** [comment]
@karthiknadig i think you can see this is a poor developer experience when switching between projects that have different preferences. Are there any roadmap ideas to make this simpler for us?
