### ISSUE TITLE
pylint.importStrategy for folder does not exist

### ISSUE THREAD

**Issue by juskek** [microsoft/vscode-pylint#377]
![image](https://github.com/microsoft/vscode-pylint/assets/57725347/23bfa6fb-2901-444a-8fff-cb316e916fa2)
![image](https://github.com/microsoft/vscode-pylint/assets/57725347/18815b3b-e155-45f7-a86d-396b343e7a51)

Would it be possible to get a folder setting for import strategy?

**Comment by juskek** [comment]
Hi! Thanks for the quick response 😃 

We've got a venv with a specific pylint version installed, and we want the pylint extension to use that version across different local machines

This feature is available with the black and isort VSCode extensions as well!

**Comment by luabud** [comment]
We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. If you're part of the event and would like to submit a contribution to this issue, please let us know, and we'll be happy to assign it to you.

For other community members who are not participating in the event, we appreciate your interest in contributing! We kindly request that you wait until after September 22nd to work on this issue. If no one from the event has been assigned to it by then, we'll gladly assign it to you. Thank you for your understanding and support!

**Comment by luabud** [comment]
This issue is about setting a changing the [scope](https://github.com/microsoft/vscode-pylint/blob/e3e7cc947681456499967284d00a21c4a1702b15/package.json#L98C27-L98C27) of the pylint.importStrategy setting. You can learn more about setting scopes here: https://code.visualstudio.com/api/references/contribution-points#contributes.configuration

**Comment by Lynanguyen0515** [comment]
Hello! I'm going to Grace Hopper this year. Could you assign me this issue? Thank you. :>

**Comment by karthiknadig** [comment]
@Lynanguyen0515 You can look at this extension to see how to adjust the scope of `importStrategy`: https://github.com/microsoft/vscode-black-formatter
