### ISSUE TITLE
Improve setting description for default interpreter setting

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-pylint#388]
Same issue as this: https://github.com/microsoft/vscode-mypy/issues/144

Improve description of the default value of the setting. When it's set to `[]`, it will use the Python extension's selected interpreter. If it's set to a path, it will use that value as the interpreter. See this PR: https://github.com/microsoft/vscode-mypy/pull/152/files

**Comment by aku1310** [comment]
Hi @luabud, hope you're doing well!
I will be participating in GHC 2023 and I am interested to work on this issue. Do we have to wait until the Open Source Day starts to be assigned an issue or could it be assigned before as well?

**Comment by luabud** [comment]
@aku1310 done!
