### ISSUE TITLE
Capitalize instances of "python" in user-facing text

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-pylint#389]
Whenever there are user facing references like in settings, commands or descriptions, we should capitalize "Python".

**Comment by HVbajoria** [comment]
Hello @luabud,
I would like to work on this issue. Can you please assign it to me? 
Thank you

**Comment by luabud** [comment]
Hi @HVbajoria! Thank you so much for your interest in contributing to our repo😊 We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. I'll add comments to reserve these issues more explicitly. But if during the event no one wants to take this issue, I'll happily assign it to you so you can contribute post the event!

**Comment by luabud** [comment]
We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. If you're part of the event and would like to submit a contribution to this issue, please let us know, and we'll be happy to assign it to you.

For other community members who are not participating in the event, we appreciate your interest in contributing! We kindly request that you wait until after September 22nd to work on this issue. If no one from the event has been assigned to it by then, we'll gladly assign it to you. Thank you for your understanding and support!

**Comment by Mprach18** [comment]
I would like to take up this issue

**Comment by nishitasinha24** [comment]
I would like to work on this issue, thanks!
