### ISSUE TITLE
Can't install Pylint stable, only pre-release, and that doesn't works.

### ISSUE THREAD

**Issue by ChekeredList71** [microsoft/vscode-pylint#39]
Hello, I am unable to install Pylint release version, only Pre-Release.
I get this message: `Can't install release version of 'ms-python.pylint' extension because it has no release version.` Currently, I cannot try to Reproduce the issue on an other computer, but tomorrow I'll try.
Yes, I know someone already asked this, but on Ubuntu and the case was a little bit different.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Windows 10

Steps to Reproduce:

1. Try installing Pylint extension.
2. See the error message.

**Comment by sandy081** [comment]
This is expected as this extension does not have any release version. Moving this issue to extension repo to decide if they would like publish a release version.

**Comment by karthiknadig** [comment]
We will publish a release version after soon. Pending enough feedback.

**Comment by JeanMesa** [comment]
Hello everyone,
Does anyone know of a workaround for this issue or if it's been mitigated? I am still unable to install get, getting the following err: "Can't install release version of 'ms-python.pylint' extension because it has no release version."
I attempted installing the "Pre-release" version but the functionality does not suffice as it's missing features.
Thanks in advance :)

**Comment by karthiknadig** [comment]
You can download and install the vsix manually from the marketplace: https://marketplace.visualstudio.com/items?itemName=ms-python.pylint

**Comment by RGBYCP** [comment]
Despite choosing the `install release version` button, I get `Can't install release version of 'ms-python.pylint' extension because it has no release version.` still.

**Comment by karthiknadig** [comment]
@RGBYCP We will publish release version soon. Until then you can install this manually by downloading the VSIX from the marketplace.

**Comment by jacobglanz** [comment]
It still doesn't work for me, can you please provide a step by step guide?

**Comment by karthiknadig** [comment]
@jacobglanz see here https://github.com/microsoft/vscode-pylint/issues/19#issuecomment-1084051282
