### ISSUE TITLE
Can't use relative rcfile

### ISSUE THREAD

**Issue by parched** [microsoft/vscode-pylint#41]
I have a multiroot workspace where one of the folders is a python project, in the root of that folder there is `.pylintrc`. The python extension picks this up automatically, I assume that's because it runs `pylint` from that folder. However, I can't seem to get it to work with this extension. I tried two things:
* Add this to the `settings.json` for the folder `"pylint.args": [ "--rcfile=${workspaceFolder}/.pylintrc" ]`
  which appears to not be picked up at all when I look at the Pylint extension logs.
* Add the same to the settings in the workspace file, but the variable isn't evaluated
```
pylint --reports=n --output-format=json --rcfile=${workspaceFolder}/.pylintrc --from-stdin path\to\file.py
[Error - 8:35:40 am] The config file ${workspaceFolder}/.pylintrc doesn't exist!
```

**Comment by karthiknadig** [comment]
@parched can you share your *.code-workspace contents?

**Comment by parched** [comment]
It looks like this
```
{
  "folders": [
    {
      "path": "excel-add-in" // not a python folder
    },
    {
      "path": "py-lib" // the python folder that contains .pylintrc
    },
    {
      "name": "root",
      "path": ".",
    }
  ],
  "settings": {
    "pylint.args": [
      "--rcfile=${workspaceFolder}/.pylintrc"
    ],
  }
}
```
this seems to work though
```
    ...
    "pylint.args": [
      "--rcfile=../py-lib/.pylintrc"
    ],
    ...
```
I now remember that I've hit this with other extensions too, the working directory is always the first folder in the workspace. So this example works for this project because there is only one `.pylintrc`. But I have another project I'd like to use this extension with that has a `.pylintrc` in each workspace folder, that won't work.

**Comment by parched** [comment]
It's also not picking up the correct interpreter (and hence pylint version). It appears to be using the global one instead of the one set for the `py-lib` folder.

**Comment by karthiknadig** [comment]
@parched Can you try the multi-root scenario and the multi-python scenario with this build? https://github.com/microsoft/vscode-pylint/suites/6116571062/artifacts/212652903

Can you also change your setting to say:
```
"pylint.args": [
      "--rcfile=./.pylintrc"
    ],
```

In the multi-root scenario the `cwd` will be the workspace folder. In multi-python scenario it will use the python set for that folder. so you shouldn't have to use `${workspaceFolder}`.

**Comment by parched** [comment]
Hi @karthiknadig, thanks, that works well. I didn't need to set `pylint.args` because pylint finds it automatically when it's in the CWD.
