### ISSUE TITLE
Unable to import '_typeshed' PylintE0401:import-error (type alias) Incomplete: Any

### ISSUE THREAD

**Issue by westforkfab** [microsoft/vscode-pylint#424]
Python 3.11.4
Generated stub file via stubgen
In the generated stubfile, Pylint complains about _typeshed import

`from _typeshed import Incomplete`

Tooltip error:
Unable to import '_typeshed'Pylint[E0401:import-error](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/import-error.html)
(module) _typeshed
Built-in functions, types, exceptions, and other objects.

This module provides direct access to all 'built-in' identifiers of Python; for example, builtins.len is the full name for the built-in function len().

This module is not normally accessed explicitly by most applications, but can be useful in modules that provide objects with the same name as a built-in value, but in which the built-in of that name is also needed.

**Comment by karthiknadig** [comment]
@westforkfab Does this happen when you run it `pylint` from terminal?

**Comment by westforkfab** [comment]
@karthiknadig no. I have pylint as extension in vscode.
I generated the stubfile using stubgen. When I open the generated file, vscode shows the line with that import underlined in red. Moving the mouse over that line, the tooltip shows the error.

**Comment by karthiknadig** [comment]
@westforkfab You might have to add the folder containing the `_typeshed` to `python.analysis.extrapaths`

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
