### ISSUE TITLE
Showing python.linting.pytlintEnabled even this setting not exist in Setting.json file

### ISSUE THREAD

**Issue by noppGithub** [microsoft/vscode-pylint#443]
Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

```log
2023-11-06 04:37:50.846 [error] Following setting is deprecated: "python.linting.pylintEnabled"
2023-11-06 04:37:50.846 [error] All settings starting with "python.linting." are deprecated and can be removed from settings.
2023-11-06 04:37:50.846 [error] Linting features have been moved to separate linter extensions.
2023-11-06 04:37:50.846 [error] See here for more information: https://code.visualstudio.com/docs/python/linting
2023-11-06 04:37:50.846 [error] Please install "pylint" extension: https://marketplace.visualstudio.com/items?itemName=ms-python.pylint
```

I have Pylint installed below however get error message when start VSCode
![pylint](https://github.com/microsoft/vscode-pylint/assets/21082770/782ecb45-b87b-470c-b4dc-903bc07c49cb)

I checked that this key not exist in my Setting.json
![pl2](https://github.com/microsoft/vscode-pylint/assets/21082770/242e6503-3e94-437f-9bf3-6fc989d36d47)

**Comment by karthiknadig** [comment]
@noppGithub There are several settings files please check the user settings and workspace settings. If you are using remote workspace, then there can be three settings json, one for user, remote machine, and workspace.

**Comment by noppGithub** [comment]
@karthiknadig Thank you so much, the issue is solved, 
It would be nice if the error log told me which settings need attention.
e.g. `Error from your User setting.json`

**Comment by marcelrv** [comment]
Seems impossible to find from which file this originates... 
Is this really and `error` as the log indicates (like something is not working) or is it more sort of warning.

**Comment by wenijinew** [comment]
How can this be closed without any action points? 😢

**Comment by karthiknadig** [comment]
@wenijinew There is no API is VS Code that tells us which particular settings.json this comes from. You have to open the settings editor and see where this might be set. Then again this is a warning in the logs, should not affect how the extension works. We will be removing the notification soon, and that notification also does not come from this extension, so there is nothing really to do for this issue in this repo.

**Comment by marcelrv** [comment]
> Then again this is a warning in the logs, should not affect how the

It is not a warning, but showing as error! In the log

**Comment by karthiknadig** [comment]
What is the version of python extension  (ms-python.python) you have installed? the latest is `2024.22.*` for stable and `2024.23.*` for pre-release. The error notification was removed https://github.com/microsoft/vscode-python/pull/24240 last year october release.
