### ISSUE TITLE
Shows "Unused Variable" warnings on .pyi files

### ISSUE THREAD

**Issue by cootshk** [microsoft/vscode-pylint#462]
See this picture:
<img width="1002" alt="image" src="https://github.com/microsoft/vscode-pylint/assets/83678457/b6ad4040-e392-44eb-b926-dabf8d7f8bd0">
The file I'm editing is `src/reddit.pyi`, while another file named `src/reddit.py` contains all the code, per PEP 561

**Comment by karthiknadig** [comment]
Please share the logs from Output > pylint for this case

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
