### ISSUE TITLE
Inconsistent treatment of python.analysis.extraPaths between pylint and pylance

### ISSUE THREAD

**Issue by couteau** [microsoft/vscode-pylint#511]
It appears that both pylance and the vscode pylint extension use the `python.analysis.extraPaths` setting when resolving imports, but that treat that setting differently with respect to relative paths and variable expansion. This is creating an issue for me in how to specify a path that is relative to the user's home directory.

In Unix-like systems (I'm on MacOS), the "\~" character at the beginning of the path means the user's home directory. Pylance will treat a path that is prefixed with "\~" correctly, and search the path relative to the user's home directory. Pylint, on the other hand, treats a path starting with "\~" as a relative path, and specifically, a path relative to the workspace folder. That results in a search path that looks, for example, like `/usr/src/project/~/anaconda3/envs/myenv/shared/package`, which doesn't work, causing pylint to fail to resolve an import that pylance has no problem with.

On the other hand, pylint will recognize and expand the standard vscode settings variable `${userHome}` when evaluating `python.analysis.extraPaths` and will successfully resolve the imports. In contrast, pylance does not recognize and expand these variables, and will choke on a path that starts with `${userHome}`, and reports that imports in that path cannot be resolved. 

I am currently working around this issue by including in the `python.analysis.extraPaths` the same path twice, once beginning with "\~" and once beginning with `${userHome}`. 

I could just make them all absolute paths, starting with my home directory, but I don't like to include personal info like that in a settings file that will be public on GitHub, and even if I were ok with that, the settings file wouldn't work for anyone else who might clone my repo.

In any event, it seems like these two python-related parts of vscode that both use the same setting should treat it the same.

**Comment by karthiknadig** [comment]
@couteau Thanks for reporting, this looks like something we can handle in the variable resolver.

Found here:
https://github.com/microsoft/vscode-pylint/blob/4fb723ba782a266fb81c06268ae10260f265b2e3/src/common/settings.ts#L35-L78

**Comment by MGasiewski** [comment]
I have a fix for this, just working out the unit test changes. Will submit PR soon.
