### ISSUE TITLE
Pylint arguments are not working

### ISSUE THREAD

**Issue by Nuho-ZubaedSalam** [microsoft/vscode-pylint#530]
Hi everyone, 
I'm having anissue with Pylint. 
Unfortunately when I put the following instructions in my `settings.json` file, the instructions aren't recognised and whenever I hover over them with my mouse, a pop-up saying **Unknown Configuration Setting** appears.

![Screenshot 2024-03-14 213030](https://github.com/microsoft/vscode-pylint/assets/111590440/29fccec7-18b5-4e42-9e87-7ad16191056b)

Can anyone help me with fixing this?
A huge hanks to everyone who does :)

**Comment by Nuho-ZubaedSalam** [comment]
Thank you very much. You're a life saver. ;)

**Comment by rahadkc** [comment]
> Use `pylint.args` , `python.linting.args` is deprecated

It works. Thanks
