### ISSUE TITLE
Autoformatting request is broken

### ISSUE THREAD

**Issue by Kein** [microsoft/vscode-pylint#536]
This exist but it does absolutely nothing:
![image](https://github.com/microsoft/vscode-pylint/assets/623756/e1f61463-49d7-4131-b465-e9b5d5e54936)
![image](https://github.com/microsoft/vscode-pylint/assets/623756/c755e8ee-9ef9-4dc0-ae68-8d6c11ba3c77)

I've went through all the extension outputs but there isnt even an indication action was dispatched.
I've tried using external `pylint` as well

Pylint extension: 2023.11.13481007
Python interp: 3.9.0
Python extension: 2024.3.10791010

**Comment by karthiknadig** [comment]
@Kein You need to install Formatting extension, and set it as the default formatter. The command there does not know if such an extension is installed or not, it will just ask VS Code to use run a formatter.


Install black, autopep8, ruff, or which ever formatter extension you want to use. Add the following to your settings:
```
 "[python]": {
        "editor.defaultFormatter": "ms-python.black-formatter" // Use ruff or autopep8 extension ID here depending on which one you have installed.
    },
```
