### ISSUE TITLE
[Feature Request] new lint rule to require a comment #. at end each code block.

### ISSUE THREAD

**Issue by EdSaleh** [microsoft/vscode-pylint#564]
Create a new rule to require that each block must end with # or #. 
This would work as a curly braces blocks found in C style languages.
Also, this could also be used to reformat python code by code editor to fix any indentation issues.

Example:

```python
import string
def atbash(sequence: str) -> str:
    """
    Example
    """
    output = ""
    for i in sequence:
        extract = ord(i)
        if 65 <= extract <= 90:
            output += chr(155 - extract)
        #.
        elif 97 <= extract <= 122:
            output += chr(219 - extract)
        #.
        else:
            output += i
        #.
    #.
    return output
#.
```

**Comment by karthiknadig** [comment]
This is just a wrapper around `pylint` for VS Code, please file this feature request on https://github.com/pylint-dev/pylint/issues

**Comment by Pierre-Sassoulas** [comment]
(pylint maintainer here), you should create your custom pylint plugin for that, enforcing a kind of 'end' keyword to make python look like pascal or ada is going to not be pythonic enough / too controversial for pylint core.
