### ISSUE TITLE
pylint extension stays disabled in windows 11 vs code after installing and cannot be enabled

### ISSUE THREAD

**Issue by shreek1861** [microsoft/vscode-pylint#582]
I do see pylint command working fine from VS code terminal.

pip show pylint
Name: pylint
Version: 3.3.2
Summary: python code static checker
Home-page: https://github.com/pylint-dev/pylint
Author:
Author-email: Python Code Quality Authority <code-quality@python.org>
License: GPL-2.0-or-later
Location: C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
Requires: astroid, colorama, dill, isort, mccabe, platformdirs, tomlkit
Required-by:

I also see the following three options are unrecognized in settings.json

  "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.lintOnSave": true,

Python extension along with pylance and python debugger extensions are working fine.

Please help.

**Comment by karthiknadig** [comment]
Can you share a screenshot of the extension from the extension view? There should be a button to enable the extension.

**Comment by shreek1861** [comment]
Please see attached.. Enable option is disabled.

![Image](https://github.com/user-attachments/assets/ef3f5b70-438f-4b1a-bd6f-3814be2a3ff3)

![Image](https://github.com/user-attachments/assets/a7e07d4a-0345-403a-a2e5-b0076cd6673f)

**Comment by karthiknadig** [comment]
Can you show me the pylint page? It is currently showing SSH FS page, I want to see what version of the extension is installed and if there are any update options. What is the version of VS code you have?

**Comment by shreek1861** [comment]
Here you go 
![Image](https://github.com/user-attachments/assets/61ceada9-14b0-40f6-918d-1e3c4648f9ba)

![Image](https://github.com/user-attachments/assets/e5395ea3-c9c9-4fc1-8224-af9c3c72aadb)

**Comment by karthiknadig** [comment]
Looks like you are using a Virtual workspace. This is not supported by the pylint extension. You need to open this as a normal workspace. Only Pylance will work in this scenario.

**Comment by shreek1861** [comment]
ok, thank you for looking into this.
