### ISSUE TITLE
Pylint Settings: Help user discover pylint options

### ISSUE THREAD

**Issue by dciborow** [microsoft/vscode-pylint#70]
Currently, the settings page provided for configuring pylint is very limited. 

In general, users are likely to use a configuration file. Having a simple setting to let the user point to the configuration file would help to reduce potential for setup mistakes. (I keep putting my args on the same line...)

VSCode could then load the completed configurations provided by the user and dispaly those in the setings.

VSCode could also use the "generate-rcfile" command, to determine the full set of configurations for pylint, and display the default settings in the UX. Then if a user changes any of the default settings then can be saved to the pointed configuration file as well.

**Comment by DanielNoord** [comment]
Note that we are currently discussing whether we want to deprecate ``generate-rcfile`` in favour of the new ``generate-toml-config`` command. So if that option is chosen, please consider using that command instead on all versions that support it. (>=2.14)

**Comment by dciborow** [comment]
Again, after installing the plugin, I still scratch my head and have to look up what the config command is.
Having a default value of config "AUTO", where vscode will search for likely files would be great too.

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
