### ISSUE TITLE
Detect version of `pylint` and notify if the version is not supported

### ISSUE THREAD

**Issue by jpmolinamatute** [microsoft/vscode-pylint#80]
Hello there!

at the moment, pylint seems like it's not running in VSCode, I have run pylint manually in the command line and I get a bunch of errors and warnings, However, vscode says 0 errors, 0 warnings.

in the root directory, I have a default .pylintrc file, I have disabled/enabled "python.linting.pylintEnabled".

in the developer console I have seen "Error: write after end" errors sometimes but another time I don't and pylint extension is still not running.

what else should I do to properly identify the root problem??

thanks in advance for your help

**Comment by karthiknadig** [comment]
@jpmolinamatute `"python.linting.pylintEnabled"` setting is used by the python extension, not the `pylint` extension.

If pylint extension is installed and enabled, you should see this in the output panel:
![image](https://user-images.githubusercontent.com/3840081/166812551-0d55a2de-8df0-466b-9f18-d3665da73bee.png)

If there are any errors you should see it in the Output > Pylint panel.

**Comment by karthiknadig** [comment]
@jpmolinamatute Can you check the version of `pylint` in your environment?

**Comment by karthiknadig** [comment]
@jpmolinamatute From the stack it looks like it is picking up the `pylint` version installed in the environment. Unless you need to work with a specific version of `pylint`, I recommend updating `pylint` and its dependencies to the latest. Minimum supported version of pylint is `2.12.2`. 

Another thing to know, the extension ships with a version of `pylint`, so you don't have to install it in your environment.

**Comment by jpmolinamatute** [comment]
thanks so much for the help! I uninstalled pylint from my venv, and as soon as the command completed vscode-pylint started working as it suppose to. :-) 


still, I think this is a bug because I didn't set `"pylint.path"` and I was assuming vscode-pylint was using its built-in pylint instead of the environment. In other words, if I have installed pylint, it will break vscode-pylint. 


one more thing I think this bug affect MacOS only because in my linux machine, I have pylint installed and vscode-pylint  worked out of the box without a problem

**Comment by karthiknadig** [comment]
@jpmolinamatute This might be a version problem. You might have had a later version on your linux machine and older one on Mac possibly. 

The order of pick up is:
1. `pylint.path` set that will be used (we recommend against it as it won't perform as efficiently)
2. `pylint` installed in the environment (but down side is if it lower than 2.12.2. it might not work)
3. `pylint` bndled with the extension.

**Comment by karthiknadig** [comment]
In cases were we might use incompatible version of pylint, we should notify the user about it, instead of falling.

**Comment by jpmolinamatute** [comment]
> @jpmolinamatute This might be a version problem. You might have had a later version on your linux machine and older one on Mac possibly.
> 
> The order of pick up is:
> 
>     1. `pylint.path` set that will be used (we recommend against it as it won't perform as efficiently)
> 
>     2. `pylint` installed in the environment (but the downside is if it is lower than 2.12.2. it might not work)
> 
>     3. `pylint` bundled with the extension.

I find this information very useful, I think it should be in the readme
